service: serverless-dynamodb-streams

provider:
  name: aws
  runtime: nodejs4.3
  iamRoleStatements:
    - Effect: "Allow"
      Resource: "*"
      Action:
        - "dynamodb:*"

functions:
  updateProfile:
    handler: handler.updateProfile
  logger:
    handler: handler.logger
    events:
      - stream: arn:aws:dynamodb:<region>:<account-id>:table/<table-name>/stream/<timestamp>
